apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.secrets.postgres.name }}"
  namespace: "{{ .Values.namespace }}"
type: Opaque
stringData:
  POSTGRES_USER: "{{ .Values.secrets.postgres.admin.name }}"
  POSTGRES_PASSWORD: "{{ .Values.secrets.postgres.admin.password }}"
  POSTGRES_DB: "{{ .Values.deployments.postgres.db.name }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.secrets.tls.name }}"
  namespace: "{{ .Values.namespace }}"
type: kubernetes.io/tls
data:
  tls.crt: "{{ .Values.secrets.tls.cert }}"
  tls.key: "{{ .Values.secrets.tls.key }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.secrets.keycloak.name }}"
  namespace: "{{ .Values.namespace }}"
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "{{ .Values.secrets.keycloak.admin.name }}"
  KEYCLOAK_ADMIN_PASSWORD: "{{ .Values.secrets.keycloak.admin.password }}"
