/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.12).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.jmk.people.api;

import java.util.List;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.jmk.people.model.Member;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-02-27T07:02:52.969Z")

@Api(value = "member", description = "the member API")
@RequestMapping(value = "/member")
public interface MemberApi {

    @ApiOperation(value = "Member Creation Service", nickname = "createMember", notes = "Member Creation Service", response = Member.class, tags={ "MemberMgmtServiceApi", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Member.class),
        @ApiResponse(code = 400, message = "Bad Request"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @RequestMapping(value = "/",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<Member> createMember(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Member body,@ApiParam(value = "" ) @RequestHeader(value="xChannel", required=false) String xChannel);


    @ApiOperation(value = "Member Creation with input arrays Service", nickname = "createMembersWithArrayInput", notes = "Member Finding Service", tags={ "MemberMgmtServiceApi", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successfully found"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @RequestMapping(value = "/createWithArray",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> createMembersWithArrayInput(@ApiParam(value = "" ,required=true )  @Valid @RequestBody List<Member> body,@ApiParam(value = "" ) @RequestHeader(value="xChannel", required=false) String xChannel);


    @ApiOperation(value = "Member Deletion Service based on the member id", nickname = "deleteMemberById", notes = "Member Deletion Service based on the member id", tags={ "MemberMgmtServiceApi", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Member deleted succussfully"),
        @ApiResponse(code = 400, message = "Invalid User id supplied"),
        @ApiResponse(code = 404, message = "Member Id not found"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @RequestMapping(value = "/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteMemberById(@ApiParam(value = "Member Id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "Find all the members by status", nickname = "findMemberByMobileNumber", notes = "Find all the members by status", response = Member.class, tags={ "MemberMgmtServiceApi", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successfully found", response = Member.class),
        @ApiResponse(code = 400, message = "Invalid Member number supplied"),
        @ApiResponse(code = 404, message = "Member not found or inactive"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @RequestMapping(value = "/findByMobileNumber",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.GET)
    ResponseEntity<Member> findMemberByMobileNumber(@ApiParam(value = "" ) @RequestHeader(value="xChannel", required=false) String xChannel,@ApiParam(value = "") @Valid @RequestParam(value = "mobileNo", required = false) String mobileNo);


    @ApiOperation(value = "Find Member Details based on the member id", nickname = "findMemberDetailsById", notes = "Find Member Details based on the member id", response = Member.class, tags={ "MemberMgmtServiceApi", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successfully found", response = Member.class),
        @ApiResponse(code = 400, message = "Invalid Member name and password supplied"),
        @ApiResponse(code = 404, message = "Member not found or inactive"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @RequestMapping(value = "/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<Member> findMemberDetailsById(@ApiParam(value = "Member Id",required=true) @PathVariable("id") Long id) ;


    @ApiOperation(value = "Find all the members by status", nickname = "findMembersByStatus", notes = "Find all the members by status", response = Member.class, responseContainer = "List", tags={ "MemberMgmtServiceApi", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Member.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Invalid status value"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @RequestMapping(value = "/findByStatus",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.GET)
    ResponseEntity<List<Member>> findMembersByStatus(@ApiParam(value = "" ) @RequestHeader(value="xChannel", required=false) String xChannel,@ApiParam(value = "The status to restrict the results to.  If not provided, all records are returned", allowableValues = "A, I") @Valid @RequestParam(value = "status", required = false) String status);


    @ApiOperation(value = "Update Member Details based on the member id", nickname = "updateMemberById", notes = "Update Member Details based on the member id", response = Member.class, tags={ "MemberMgmtServiceApi", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successfully found", response = Member.class),
        @ApiResponse(code = 400, message = "Invalid Member name supplied"),
        @ApiResponse(code = 404, message = "Member not found or inactive"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @RequestMapping(value = "/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Member> updateMemberById(@ApiParam(value = "Member Id",required=true) @PathVariable("id") Long id,@ApiParam(value = "" ,required=true )  @Valid @RequestBody Member body) ;

}
