/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.12).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.jmk.people.api;

import java.util.List;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.jmk.people.model.Sevadar;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-02-27T07:02:52.969Z")

@Api(value = "sevadar", description = "the sevadar API")
@RequestMapping(value = "/api/")
public interface SevadarApi {

    @ApiOperation(value = "Sevadar Creation Service", nickname = "createSevadar", notes = "Sevadar Creation Service", response = Sevadar.class, tags={ "SevadarMgmtServiceApi", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Sevadar.class),
        @ApiResponse(code = 400, message = "Bad Request"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @RequestMapping(value = "/sevadar",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<Sevadar> createSevadar(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Sevadar body,@ApiParam(value = "" ) @RequestHeader(value="xChannel", required=false) String xChannel);

    @ApiOperation(value = "Sevadar Creation with input arrays Service", nickname = "createSevadarsWithArrayInput", notes = "Sevadar Finding Service", tags={ "SevadarMgmtServiceApi", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successfully found"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @RequestMapping(value = "/sevadar/createWithArray",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> createSevadarsWithArrayInput(@ApiParam(value = "" ,required=true )  @Valid @RequestBody List<Sevadar> body,@ApiParam(value = "" ) @RequestHeader(value="xChannel", required=false) String xChannel);


    @ApiOperation(value = "Sevadar Deletion Service based on the sevadar id", nickname = "deleteSevadarById", notes = "Sevadar Deletion Service based on the sevadar id", tags={ "SevadarMgmtServiceApi", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Sevadar deleted succussfully"),
        @ApiResponse(code = 400, message = "Invalid User id supplied"),
        @ApiResponse(code = 404, message = "Sevadar Id not found"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @RequestMapping(value = "/sevadar/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteSevadarById(@ApiParam(value = "Sevadar Id",required=true) @PathVariable("id") Long id) ;


    @ApiOperation(value = "Find the sevadar by mobile number", nickname = "findSevadarByMobileNumber", notes = "Find the sevadar by mobile number", response = Sevadar.class, tags={ "SevadarMgmtServiceApi", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successfully found", response = Sevadar.class),
        @ApiResponse(code = 400, message = "Invalid mobile number supplied"),
        @ApiResponse(code = 404, message = "Sevadar not found or inactive"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @RequestMapping(value = "/sevadar/findByMobileNumber",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.GET)
    ResponseEntity<Sevadar> findSevadarByMobileNumber(@ApiParam(value = "" ) @RequestHeader(value="xChannel", required=false) String xChannel,@ApiParam(value = "") @Valid @RequestParam(value = "mobileNo", required = false) String mobileNo) ;


    @ApiOperation(value = "Find Sevadar Details based on the sevadar id", nickname = "findSevadarDetailsById", notes = "Find Sevadar Details based on the sevadar id", response = Sevadar.class, tags={ "SevadarMgmtServiceApi", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successfully found", response = Sevadar.class),
        @ApiResponse(code = 400, message = "Invalid Sevadar name and password supplied"),
        @ApiResponse(code = 404, message = "Sevadar not found or inactive"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @RequestMapping(value = "/sevadar/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<Sevadar> findSevadarDetailsById(@ApiParam(value = "Sevadar Id",required=true) @PathVariable("id") Long id) ;


    @ApiOperation(value = "Find the sevadars by status", nickname = "findSevadarsByStatus", notes = "Find all the sevadars by status", response = Sevadar.class, responseContainer = "List", tags={ "SevadarMgmtServiceApi", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Sevadar.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Invalid status value"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @RequestMapping(value = "/sevadar/findByStatus",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.GET)
    ResponseEntity<List<Sevadar>> findSevadarsByStatus(@ApiParam(value = "" ) @RequestHeader(value="xChannel", required=false) String xChannel,@ApiParam(value = "The status to restrict the results to.  If not provided, all records are returned", allowableValues = "A, I") @Valid @RequestParam(value = "status", required = false) String status) ;


    @ApiOperation(value = "Update Sevadar Details based on the sevadar id", nickname = "updateSevadarById", notes = "Update Sevadar Details based on the sevadar id", response = Sevadar.class, tags={ "SevadarMgmtServiceApi", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successfully found", response = Sevadar.class),
        @ApiResponse(code = 400, message = "Invalid Sevadar name supplied"),
        @ApiResponse(code = 404, message = "Sevadar not found or inactive"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @RequestMapping(value = "/sevadar/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Sevadar> updateSevadarById(@ApiParam(value = "Sevadar Id",required=true) @PathVariable("id") Long id,@ApiParam(value = "" ,required=true )  @Valid @RequestBody Sevadar body);

}
