# Default values for user-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: "bjjd-system"

config:
   springActiveProfile: "kubernetes"
   databaseHostname: "to-be-fetched-from-hashicorp-vault"
   databaseRootUser: "to-be-fetched-from-hashicorp-vault"
   databaseName: "users_db"
   databasePort: "3306"
   databaseUsername: "to-be-fetched-from-hashicorp-vault"
   
secret:
    databaseRootPassword: "to-be-fetched-from-hashicorp-vault"
    databasePassword: "to-be-fetched-from-hashicorp-vault"
    

replicaCount: 1

image:
  repository: rajivbansal2981/user-service
  pullPolicy: Always #IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0.1.RELEASE"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 3379
  nodePort: 32319


resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1
    memory: 0.50Gi
  requests:
    cpu: .25
    memory: 0.50Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
