apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1000Mi
  accessModes:
    - ReadWriteOnce #Persistent volume claims 1000Mi from storage with ReadWriteOne access mode.
  hostPath:
    path: "/mnt/data" #Host path is /mnt/data where all our data will reside.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: project-service #Request of the storage for project-service that can be fulfilled by PV.
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi #Request for the amount of storage