apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  database_root_password: {{ .Values.secret.databaseRootPassword | quote }} #My sql root password:bjjd
  database_password: {{ .Values.secret.databasePassword | quote }}
  VAULT_TOKEN: 18456350-7b89-11ed-85e9-a5830358e351
