apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  database_root_password: {{ .Values.secret.databaseRootPassword | quote }} #My sql root password:bjjd
  database_password: {{ .Values.secret.databasePassword | quote }}
