apiVersion: v1
kind: Service
metadata:
  name: {{ include "people-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "people-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 5701
      name: hazelcast
  selector:
    {{- include "people-service.selectorLabels" . | nindent 4 }}