apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap}}
  namespace: {{ .Values.namespace}}
data:
  "spring.active.profile": "prod"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name}}
  namespace: {{ .Values.namespace}}
  labels:
    app: {{ .Values.name}}
spec:
  replicas: {{ .Values.replicas}}
  minReadySeconds: 45
  selector:
    matchLabels:
      app: {{ .Values.name}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.name}}
    spec:
      hostname: busybox-1
      subdomain: default-subdomain
      containers:
      - name: {{ .Values.name}}
        image: {{ .Values.image}}
        imagePullPolicy: Always #IfNotPresent
        ports:
          - name: http
            containerPort: {{ .Values.port}} # The port that the container exposes
        env:
        - name: SPRING_ACTIVE_PROFILE
          valueFrom: 
             configMapKeyRef:
                 name: {{ .Values.configmap}}
                 key: spring.active.profile
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name}}
  namespace: {{ .Values.namespace}}
  labels: #PODS
    app: {{ .Values.name}}
spec:
  type: {{ .Values.servicetype}} #NodePort or LoadBalancer or ClusterIP
  selector:
    app: {{ .Values.name}}
  ports:
   - name: app
     port: {{ .Values.port}}