apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name}}
  namespace: {{ .Values.namespace}}
  labels: #PODS
    app: {{ .Values.name}}
spec:
  type: {{ .Values.servicetype}} #NodePort or LoadBalancer or ClusterIP
  selector:
    app: {{ .Values.name}}
  ports:
   - name: hazelcast
     port: 5701
   - name: app
     port: {{ .Values.port}}