apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway-service
  labels:
    app: cloud-gateway-service
  #namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: cloud-gateway-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cloud-gateway-service
    spec:
      containers:
      - name: cloud-gateway-service
        image: rajivbansal2981/cloud-gateway-service:0.0.1.RELEASE
        imagePullPolicy: IfNotPresent #IfNotPresent or Always
        ports:
          - name: http
            containerPort: 8080 # The port that the container exposes
        env:
        - name: SPRING_ACTIVE_PROFILE
          valueFrom: 
             configMapKeyRef:
                 name: cloud-gateway-service-configmap
                 key: spring.active.profile
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-service
  labels: #PODS
    app: cloud-gateway-service
  namespace: default
spec:
  type: LoadBalancer #NodePort or LoadBalancer or ClusterIP
  selector:
    app: cloud-gateway-service
  ports:
   - name: http
     port: 8080
     targetPort: 8080