{
   "swagger":"2.0",
   "info":{
      "version":"18.10.0",
      "title":"Account Management Service API"
   },
   "basePath":"/bjjd/",
   "tags":[
      {
         "name":"AccountMgmt"
      }
   ],
   "schemes":[
      "https"
   ],
   "paths":{
      "/donation":{
         "post":{
            "tags":[
               "AccountMgmt"
            ],
            "summary":"Save Donation Service",
            "description":"Save Donation Service",
            "operationId":"saveDonation",
            "consumes":[
               "application/json",
               "application/xml"
            ],
            "produces":[
               "application/json",
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"xChannel",
                  "in":"header",
                  "required":false,
                  "type":"string",
                  "minLength":3,
                  "maxLength":36
               },
               {
                  "in":"body",
                  "name":"body",
                  "required":true,
                  "schema":{
                     "$ref":"#/definitions/Donation"
                  }
               }
            ],
            "responses":{
               "200":{
                  "description":"OK",
                  "schema":{
                     "$ref":"#/definitions/Donation"
                  }
               },
               "400":{
                  "description":"Bad Request"
               },
               "500":{
                  "description":"Internal Server Error"
                }
            }
         }
      },
    "/donation/saveWithArray":{
    "post":{
      "tags":[
        "AccountMgmt"
      ],
      "summary":"Saving Donations with input arrays Service",
            "description":"Saving Donations",
            "operationId":"saveDonations",
       "consumes":[
               "application/json"
            ],
            "produces":[
               "application/json"
            ],
      "parameters":[
               {
                  "name":"xChannel",
                  "in":"header",
                  "required":false,
                  "type":"string",
                  "minLength":3,
                  "maxLength":36
               },
               {
                  "in":"body",
                  "name":"body",
                  "required":true,
                  "schema":{
           "type" :"array",
           "items":{
            "$ref":"#/definitions/Donation"
           }
                  }
               }
            ],
      "responses":{
               "200":{
                  "description":"Successfully found"
                 
               },
               "500":{
                  "description":"Internal Server Error"
               }
            }
    }
    },
    "/expense":{
         "post":{
            "tags":[
               "AccountMgmt"
            ],
            "summary":"Save Expense Service",
            "description":"Save Expense Service",
            "operationId":"saveExpense",
            "consumes":[
               "application/json",
               "application/xml"
            ],
            "produces":[
               "application/json",
               "application/xml"
            ],
            "parameters":[
               {
                  "name":"xChannel",
                  "in":"header",
                  "required":false,
                  "type":"string",
                  "minLength":3,
                  "maxLength":36
               },
               {
                  "in":"body",
                  "name":"body",
                  "required":true,
                  "schema":{
                     "$ref":"#/definitions/Expense"
                  }
               }
            ],
            "responses":{
               "200":{
                  "description":"OK",
                  "schema":{
                     "$ref":"#/definitions/Expense"
                  }
               },
               "400":{
                  "description":"Bad Request"
               },
               "500":{
                  "description":"Internal Server Error"
                }
            }
         }
      },
    "/expense/saveWithArray":{
    "post":{
      "tags":[
        "AccountMgmt"
      ],
      "summary":"Saving Expenses with input arrays Service",
            "description":"Saving Expenses",
            "operationId":"saveExpenses",
       "consumes":[
               "application/json"
            ],
            "produces":[
               "application/json"
            ],
      "parameters":[
               {
                  "name":"xChannel",
                  "in":"header",
                  "required":false,
                  "type":"string",
                  "minLength":3,
                  "maxLength":36
               },
               {
                  "in":"body",
                  "name":"body",
                  "required":true,
                  "schema":{
           "type" :"array",
           "items":{
            "$ref":"#/definitions/Expense"
           }
                  }
               }
            ],
      "responses":{
               "200":{
                  "description":"Successfully found"
                 
               },
               "500":{
                  "description":"Internal Server Error"
               }
            }
    }
    }
   },
   "definitions":{
      "Donation":{
         "required":[
            "projectName"
         ],
         "properties":{
            "id":{
               "type":"integer",
               "format":"int64",
               "description":"donation id"
            },
      "donationDate":{
               "type":"string",
               "format":"date",
               "description":"Donation date"
            },
      "amount": {
          "type": "number",
          "minimum": 0.01,
          "maximum": 9999999999999.99,
          "description": "Amount"
      },
      "projectId":{
               "type":"integer",
               "format":"int32",
               "description":"Project Id"
            },
      "projectName":{
               "type":"string",
               "minLength":1,
               "maxLength":150,
               "description":"Project Id"
            },
      "donorType":{
               "type":"string",
               "enum": ["MEMBER","SEVADAR,","DEVOTEE"],
               "description":"Password of the user"
            },
            "donorId":{
               "type":"string",
               "minLength":1,
               "maxLength":50,
               "description":"Donor Id"
            },
            "donorName":{
               "type":"string",
               "minLength":1,
               "maxLength":255,
               "description":"Donor name"
            },
      "donorCity":{
               "type":"string",
               "minLength":1,
               "maxLength":255,
               "description":"Donor name"
            },
      "donorMobileNo":{
               "type":"string",
               "minLength":1,
               "maxLength":15,
               "description":"Donor name"
            },
      "donorPANNo":{
               "type":"string",
               "minLength":1,
               "maxLength":15,
               "description":"Donor name"
            },
      "reference":{
               "type":"string",
               "minLength":1,
               "maxLength":50,
               "description":"Password of the user"
            },
      "receivedBy":{
               "type":"integer",
               "format":"int64",
               "description":"User Group"
            },
            "description":{
               "type":"string",
               "minLength":1,
               "maxLength":250,
               "description":"Password of the user"
            },
      "remarks":{
               "type":"string",
               "minLength":1,
               "maxLength":250,
               "description":"Password of the user"
            },
            "status":{
               "type":"string",
               "enum": ["A","I"],
               "description":"Password of the user"
            },
            "groupId":{
               "type":"integer",
               "format":"int32",
               "description":"User Group"
            }
        }
      },
    "Expense":{
         "required":[
            "projectName"
         ],
         "properties":{
            "id":{
               "type":"integer",
               "format":"int64",
               "description":"donation id"
            },
      "expenseDate":{
               "type":"string",
               "format":"date",
               "description":"Donation date"
            },
      "description":{
               "type":"string",
               "minLength":1,
               "maxLength":250,
               "description":"Password of the user"
            },
      "amount": {
          "type": "number",
          "minimum": 0.01,
          "maximum": 9999999999999.99,
          "description": "Amount"
        },
      "projectId":{
               "type":"integer",
               "format":"int32",
               "description":"Project Id"
            },
      "projectName":{
               "type":"string",
               "minLength":1,
               "maxLength":150,
               "description":"Project Id"
            },
      "paidTo":{
               "type":"string",
               "minLength":1,
               "maxLength":150,
               "description":"Project Id"
            },
      "remarks":{
               "type":"string",
               "minLength":1,
               "maxLength":250,
               "description":"Password of the user"
            },
      "approvedBy":{
               "type":"integer",
               "format":"int64",
               "description":"User Group"
            },
            "status":{
               "type":"string",
               "enum": ["A","I"],
               "description":"Password of the user"
            },
            "groupId":{
               "type":"integer",
               "format":"int32",
               "description":"User Group"
            }
        }
      }
    }
}