apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bjjd-system
configMapGenerator:
- name: gateway-service-configmap
  literals:
  - application.port=1379
  - spring.active.profile=prod
resources: #Adding the following yaml resources
  - deployment.yaml