apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-upload-service
  labels:
    app: data-upload-service
  #namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: data-upload-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: data-upload-service
    spec:
      containers:
      - name: data-upload-service
        image: rajivbansal2981/data-upload-service:0.0.1.RELEASE
        imagePullPolicy: Always #IfNotPresent
        ports:
          - name: http
            containerPort: 8379 # The port that the container exposes
        env:
        - name: SPRING_ACTIVE_PROFILE
          valueFrom: 
             configMapKeyRef:
                 name: data-upload-service-configmap
                 key: spring.active.profile
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: data-upload-service
  labels: #PODS
    app: data-upload-service
  namespace: default
spec:
  type: ClusterIP #NodePort or LoadBalancer or ClusterIP
  selector:
    app: data-upload-service
  ports:
   - name: app
     port: 8379