apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-mgmt-service
  labels:
    app: project-mgmt-service
  #namespace: defaul t
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: project-mgmt-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: project-mgmt-service
    spec:
      containers:
      - name: project-mgmt-service
        image: rajivbansal2981/project-mgmt-service:0.0.1-RELEASE
        imagePullPolicy: IfNotPresent #Always
        ports:
          - name: http
            containerPort: 5379 # The port that the container exposes
        env:
        - name: DB_HOSTNAME
          valueFrom:
             configMapKeyRef:
              name: project-mgmt-service-configmap
              key: database.hostname #MySQL db host name
        - name: DB_NAME
          valueFrom: 
             configMapKeyRef:
                 name: project-mgmt-service-configmap
                 key: database.name
        - name: DB_USERNAME
          valueFrom: 
             configMapKeyRef:
                 name: project-mgmt-service-configmap
                 key: database.username
        - name: DB_PASSWORD
          valueFrom:
             secretKeyRef:
                name: project-mgmt-service-secrets
                key: database.password
        - name: DB_PORT
          valueFrom: 
             configMapKeyRef:
                 name: project-mgmt-service-configmap
                 key: database.port
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: project-mgmt-service
  labels: #PODS
    app: project-mgmt-service
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    port: 5379
    targetPort: 5379
  selector:
    app: project-mgmt-service